### ISSUE TITLE
Open source licensed?

### ISSUE THREAD

**Issue by gatewaynode** [aneeshdurg/hostfile#1]
I'd like to use your crate but there is no licensing.  If you haven't decided on one yet I'd recommend MIT or Apache licenses, but whatever you'd prefer at least something would be helpful.

**Comment by aneeshdurg** [comment]
Ah, I marked the crate as MIT licensed in `Cargo.toml` but forgot to include the license file.. I'll fix that. Thanks for pointing this out!

**Comment by gatewaynode** [comment]
Thank you!
