### ISSUE TITLE
Whitespace should be allowed, but only space is recognized

### ISSUE THREAD

**Issue by god-anubis** [aneeshdurg/hostfile#4]
https://github.com/aneeshdurg/hostfile/blob/7d03a0bd492ee25a24b269708a7ea5193dbc8641/src/lib.rs#L61

This line should allow for both space and tab
e.g.
 Some(' ') | Some ('\t') => {},

**Comment by aneeshdurg** [comment]
Thanks for opening this! Looks like the spec even specifically mentions that tabs should be allowed :facepalm:
